[package]
name = "rustpe"
version = "0.1.0"
authors = ["Willy Aguirre <marti1125@gmail.com>"]

[dependencies]
rocket = "0.3.2"
rocket_codegen = "0.3.2"

[dependencies.rocket_contrib]
version = "0.3.2"
default-features = false
features = ["json", "handlebars_templates", "tera_templates"]
