[package]
name = "rustpe"
version = "0.1.0"
authors = ["Willy Aguirre <marti1125@gmail.com>"]

[dependencies]
rocket = "0.2.5"
rocket_codegen = "0.2.5"

[dependencies.rocket_contrib]
version = "0.2.5"
default-features = false
features = ["handlebars_templates", "tera_templates"]
